version: '2.1'

services:
  node-docker:
    image: node-docker
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"